CREATE DATABASE IF NOT EXISTS web_mail;
USE web_mail;

CREATE TABLE IF NOT EXISTS `SPRING_SESSION` (
    `SESSION_ID` VARCHAR(255) NOT NULL PRIMARY KEY,
    `CREATED` BIGINT NOT NULL,
    `LAST_ACCESS_TIME` BIGINT NOT NULL,
    `MAX_INACTIVE_INTERVAL` INT NOT NULL,
    `EXPIRY_TIME` BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS `SPRING_SESSION_ATTRIBUTES` (
    `SESSION_ID` VARCHAR(255) NOT NULL,
    `ATTRIBUTE_NAME` VARCHAR(255) NOT NULL,
    `ATTRIBUTE_BYTES` BLOB NOT NULL,
    PRIMARY KEY (`SESSION_ID`, `ATTRIBUTE_NAME`),
    FOREIGN KEY (`SESSION_ID`) REFERENCES `SPRING_SESSION` (`SESSION_ID`) ON DELETE CASCADE
);